### ISSUE TITLE
Worked in codespaces on ubuntu

### ISSUE THREAD

**Issue by dfinke** [dfinke/PowerShellAI#109]
@ShaunLawrie

![image](https://user-images.githubusercontent.com/67258/232329974-3e436154-8f4b-48e5-9f48-900e39edb56a.png)

**Comment by dfinke** [comment]
I need to figure out why if does not find it. Will try to upgrade shortly.

![image](https://user-images.githubusercontent.com/67258/232334598-edd4a83a-4c54-4953-ab5d-802879d1ea53.png)

**Comment by dfinke** [comment]
On Linux I see the rate limit is being emitted but not on my windows box

**Comment by ShaunLawrie** [comment]
I'd double check on linux you're not using a different API key, that's why I added the rate limit check because my trial key had expired on one of my laptops and I was limited to 3 api calls per minute which became an obvious problem.

`Invoke-Formatter` doesn't support pipeline input until version 1.21, I'll just use the named parameter

**Comment by dfinke** [comment]
Thanks, yeah I have only one key. I need to investigate
