### ISSUE TITLE
Write-Codeblock doesn't respect spacing 

### ISSUE THREAD

**Issue by dfinke** [dfinke/PowerShellAI#132]
@ShaunLawrie 

I asked GPT to create a something that returns yaml. It did not respect the spacing.

I did not inspect the string returned. Other `gpt` type queries return yaml formatted correctly.

```
1 name: Cron Job
2 on:
3 schedule:
4 - cron: '0 1 * * 2'
5 jobs:
6 build:
7 runs-on: ubuntu-latest
8 steps:
9 - run: echo "Running cron job"
```

**Comment by ShaunLawrie** [comment]
Were you also using `Invoke-Formatter`? I only use that in functionbuilder because I know it's powershell, if you use it on raw text you'll get weird results. I can't seem to reproduce it with `Write-CodeBlock` by itself.  

> **Warning**  
> Invoke-Formatter removes leading space from non-powershell code/text  

![image](https://github.com/dfinke/PowerShellAI/assets/13159458/0a682de4-bd41-4a85-9e4b-65c4c638feeb)  

> **Note**  
> Write-CodeBlock retains leading spaces if used by itself  

![image](https://github.com/dfinke/PowerShellAI/assets/13159458/f2cce728-3bd7-4cd7-b928-0e4fd16a1770)

**Comment by dfinke** [comment]
Thanks for tracking that down. Wonder if there is a way, like vs code dues, to quickly do language detection? Then don’t use the formatter.
