### ISSUE TITLE
Ability to provide API Key via secure string

### ISSUE THREAD

**Issue by kborowinski** [dfinke/PowerShellAI#47]
As option to storing API key in environment variable, user should be able to specify the key using secure string.

**Comment by dfinke** [comment]
Thank you, that has been requested. Happy to take a PR for that. Needs to be optional so folks can get up and running quickly with the current approach.

Otherwise, you need to roll your own.

You can apply spending limits on your key as a stop gap. Plus, if someone got your key. they'd have to be processing huge, huge amounts of prompts to run up a bill of $20.

**Comment by kborowinski** [comment]
Thanks for merging the PR.
